project:
  type: website

website:
  title: "IS415_GAA"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands_on_Ex/Hands_on_Ex01.qmd"
            
            
      - text: "In-Class Exercise"
        menu:
          - text: "In-Class Exercise 2"
            href: "In_Class_Ex/In_Class_Ex02/In_Class_Ex02.qmd"
          - text: "In-Class Exercise 3"
            href: "In_Class_Ex/In_Class_Ex03/In_Class_Ex03.qmd"
          - text: "In-Class Exercise 4"
            href: "In_Class_Ex/In_Class_Ex04/In_Class_Ex04.qmd"
            
      - text: "Take-Home Exercise"
        menu: 
          - text: "Take-Home Exercise 1"
            href: "Take_Home_Ex/Take_Home_Ex01/Take_Home_Ex01.qmd"
    right: 
      - href: index.qmd
        text: Home

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

