project:
  type: website

website:
  title: "Kelly's IS415 GAA"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands_on_Ex/Hands_on_Ex01.qmd"
          - text: "Hands-on Exercise 2"
            href: "Hands_on_Ex/Hands_on_Ex02/Hands_on_Ex02.qmd"
            
            
      - text: "In-Class Exercise"
        menu:
          - text: "In-Class Exercise 2"
            href: "In_Class_Ex/In_Class_Ex02/In_Class_Ex02.qmd"
          - text: "In-Class Exercise 3"
            href: "In_Class_Ex/In_Class_Ex03/In_Class_Ex03.qmd"
          - text: "In-Class Exercise 4"
            href: "In_Class_Ex/In_Class_Ex04/In_Class_Ex04.qmd"
          - text: "In-Class Exercise 5"
            href: "In_Class_Ex/In_Class_Ex05/In_Class_Ex05.qmd"
          - text: "In-Class Exercise 6"
            href: "In_Class_Ex/In_Class_Ex06/In_Class_Ex06.qmd"
          - text: "In-Class Exercise 7"
            href: "In_Class_Ex/In_Class_Ex07/In_Class_Ex07.qmd"
          - text: "In-Class Exercise 8"
            href: "In_Class_Ex/In_Class_Ex08/In_Class_Ex08.qmd"
          - text: "In-Class Exercise 9"
            href: "In_Class_Ex/In_Class_Ex09/In_Class_Ex09.qmd"

            
      - text: "Take-Home Exercise"
        menu: 
          - text: "Take-Home Exercise 1"
            href: "Take_Home_Ex/Take_Home_Ex01/Take_Home_Ex01.qmd"
          - text: "Take-Home Exercise 2"
            href: "Take_Home_Ex/Take_Home_Ex02_EndMonths/Take_Home_Ex02.qmd"
          - text: "Take-Home Exercise 3"
            href: "Take_Home_Ex/Take_Home_Ex03/Take_Home_Ex03.qmd"
          - text: "Take-Home Exercise 3 Updated"
            href: "Take_Home_Ex/Take_Home_Ex03/Take_Home_Ex03_Updated.qmd"
            
    right: 
      - href: index.qmd
        text: Home

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

